###maintained by Divya Kashyap
###yaml file to deploy python app onto OKE with ATP integration

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp
          image: kashyap93/pythondbcs:1.0
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: app-svc-secrets
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: app-svc-secrets
                  key: password
            - name: service_name
              valueFrom:
                secretKeyRef:
                  name: app-svc-secrets
                  key: service_name
            - name: dbhostIP
              valueFrom:
                secretKeyRef:
                  name: app-svc-secrets
                  key: dbhostIP
            - name: table_name
              valueFrom:
                secretKeyRef:
                  name: app-svc-secrets
                  key: table_name
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: pythonapp
  type: NodePort
