apiVersion: v1
kind: Secret
metadata:
  name: pythonapp-svc-secrets
data:
  username: c3lzdGVt
  password: QUJLS190dF8zM0FCS0dfdHRfMzM=
  service_name: U2NvdGlhREJfeXl6MWNjLmRhdGFiYXNlc3VibmV0LnNjb3RpYWJhbmt2Y24ub3JhY2xldmNuLmNvbQ==
  dbhostIP: MTAuMC4xLjI=
  table_name: tbd
